language: node_js
node_js:
    - "14"
script:
    - npm run build
before_script:
    - npm install
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: build
    on:
        branch: master