language: node_js
node_js:
    - "stable"
cache:
    directories:
        - node_modules
before_script:
    - npm install
    - "git config user.name Travis-CI"
    - "git config user.email ci@travis-ci.org"
script:
    - npm run deploy